# Generated by Django 3.0.5 on 2020-04-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_site', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=100)),
                ('sigle', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=30)),
                ('commune', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('pepfar', models.CharField(max_length=10)),
                ('contact_1', models.CharField(max_length=100)),
                ('tel_1', models.CharField(max_length=100)),
                ('contact_2', models.CharField(max_length=100)),
                ('tel_2', models.CharField(max_length=100)),
                ('fai', models.CharField(max_length=100)),
                ('internet', models.CharField(max_length=15)),
                ('isante', models.CharField(max_length=15)),
                ('fingerprint', models.CharField(max_length=15)),
            ],
        ),
    ]
