# Generated by Django 3.0.5 on 2020-05-01 21:41

from django.db import migrations, models

def init_bd_values(apps,schema_editor):
	Region = apps.get_model('smonitoring','Region')
	Region.objects.create(code='R1',nom_region='Centre')
	Region.objects.create(code='R2',nom_region='Nord')
	Region.objects.create(code='R3',nom_region='Sud')
	
	Departement = apps.get_model('smonitoring','Departement')
	Departement.objects.create(code='OE',nom_departement='Ouest',region=Region.objects.get(code='R1'))
	Departement.objects.create(code='NO',nom_departement='Nord',region=Region.objects.get(code='R2'))
	Departement.objects.create(code='NE',nom_departement='Nord-Est',region=Region.objects.get(code='R2'))
	Departement.objects.create(code='NW',nom_departement='Nord-Ouest',region=Region.objects.get(code='R2'))
	Departement.objects.create(code='SU',nom_departement='Sud',region=Region.objects.get(code='R3'))
	Departement.objects.create(code='SE',nom_departement='Sud-Est',region=Region.objects.get(code='R3'))
	Departement.objects.create(code='AR',nom_departement='Artibonite',region=Region.objects.get(code='R2'))
	Departement.objects.create(code='NP',nom_departement='Nippes',region=Region.objects.get(code='R3'))
	Departement.objects.create(code='GA',nom_departement='Grand-Anse',region=Region.objects.get(code='R3'))
	Departement.objects.create(code='CE',nom_departement='Centre',region=Region.objects.get(code='R1'))
	
	Poste = apps.get_model('smonitoring','Poste')
	Poste.objects.create(nom_poste='Office Manager',categorie_poste='C4',domaine_poste='Gestion et Administration',dept='HR')
	Poste.objects.create(nom_poste='IT Manager',categorie_poste='C3',domaine_poste='Computers',dept='Information & technology')
	Poste.objects.create(nom_poste='IT Assistant',categorie_poste='C2',domaine_poste='Computers',dept='Information & technology')
	
	RaisonsEvenement = apps.get_model('smonitoring','RaisonsEvenement')
	RaisonsEvenement.objects.create(code_ev='',desc_ev='N/A')
	RaisonsEvenement.objects.create(code_ev='',desc_ev='Problème FAI')
	RaisonsEvenement.objects.create(code_ev='',desc_ev='Problème Interne')
	RaisonsEvenement.objects.create(code_ev='',desc_ev='Problème interne non identifié')
	RaisonsEvenement.objects.create(code_ev='',desc_ev='Source non identifié')
	RaisonsEvenement.objects.create(code_ev='',desc_ev='Problème Routeur')
	RaisonsEvenement.objects.create(code_ev='',desc_ev='Problème Eléctricité')
	RaisonsEvenement.objects.create(code_ev='',desc_ev='UPS Disfonctionnel')
	RaisonsEvenement.objects.create(code_ev='',desc_ev='Config. Instable')
	RaisonsEvenement.objects.create(code_ev='',desc_ev='Internet Lent')
	RaisonsEvenement.objects.create(code_ev='',desc_ev='Installation Incomplete')
	RaisonsEvenement.objects.create(code_ev='',desc_ev='Non Installé')
	RaisonsEvenement.objects.create(code_ev='',desc_ev='Non mentioné')

class Migration(migrations.Migration):

    dependencies = [
        ('smonitoring', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_bd_values),
    ]
