# Generated by Django 3.0.5 on 2020-04-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smonitoring', '0002_auto_20200429_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='code',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
